 # Utiliser l'image Node officielle
 FROM node:18

 # Créer le répertoire de l'application dans le conteneur
 WORKDIR /app
 
 # Copier les fichiers package.json et package-lock.json
 COPY ../../package*.json ./
 
 # Installer les dépendances
 RUN npm install
 
 # Copier le reste des fichiers du projet
 COPY ../../ .
 
 # Construire l'application
 RUN npm run build
 
 # Exposer le port que l'application utilisera
 EXPOSE 3000
 
 # Démarrer l'application
 CMD ["npm", "run", "dev"]